"""Added creator to terrain

Revision ID: 29e372846298
Revises: 22570f3ce6df
Create Date: 2025-04-21 19:53:25.392509

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '29e372846298'
down_revision: Union[str, None] = '22570f3ce6df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terrains', sa.Column('creator', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'terrains', 'users', ['creator'], ['uuid'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'terrains', type_='foreignkey')
    op.drop_column('terrains', 'creator')
    # ### end Alembic commands ###
