"""Modified filestorage table

Revision ID: 314a40857cc2
Revises: 29e372846298
Create Date: 2025-04-26 13:22:23.962583

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '314a40857cc2'
down_revision: Union[str, None] = '29e372846298'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('file_storage_filename_key', 'file_storage', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('file_storage_filename_key', 'file_storage', ['filename'])
    # ### end Alembic commands ###
