"""Added public field to terrain

Revision ID: a7d89850064e
Revises: bfaddaae24e1
Create Date: 2025-04-20 20:08:53.204736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a7d89850064e'
down_revision: Union[str, None] = 'bfaddaae24e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('terrains', sa.Column('isPublic', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('terrains', 'isPublic')
    # ### end Alembic commands ###
