"""Added some columns

Revision ID: bfaddaae24e1
Revises: d2eb6ca1e0ba
Create Date: 2025-04-20 20:02:15.142751

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bfaddaae24e1'
down_revision: Union[str, None] = 'd2eb6ca1e0ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('terrains',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('heightmapResolution', sa.Integer(), nullable=False),
    sa.Column('widthmapResolution', sa.Integer(), nullable=False),
    sa.Column('size_X', sa.Integer(), nullable=False),
    sa.Column('size_Y', sa.Integer(), nullable=False),
    sa.Column('size_Z', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('file_storage',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('terrain_uuid', sa.UUID(), nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('filetype', sa.Enum('Texture', 'Heightmap', name='filetype'), nullable=False),
    sa.Column('file_data', sa.LargeBinary(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['terrain_uuid'], ['terrains.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('filename'),
    sa.UniqueConstraint('uuid')
    )
    op.create_table('terrain_levels',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('uuid', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('terrain_uuid', sa.UUID(), nullable=False),
    sa.Column('start_X', sa.Float(), nullable=False),
    sa.Column('start_Y', sa.Float(), nullable=False),
    sa.Column('start_Z', sa.Float(), nullable=False),
    sa.Column('end_X', sa.Float(), nullable=False),
    sa.Column('end_Y', sa.Float(), nullable=False),
    sa.Column('end_Z', sa.Float(), nullable=False),
    sa.Column('creator', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['creator'], ['users.uuid'], ),
    sa.ForeignKeyConstraint(['terrain_uuid'], ['terrains.uuid'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name'),
    sa.UniqueConstraint('uuid')
    )
    op.drop_table('player_stats')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_stats',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='player_stats_pkey')
    )
    op.drop_table('terrain_levels')
    op.drop_table('file_storage')
    op.drop_table('users')
    op.drop_table('terrains')
    # ### end Alembic commands ###
