"""Scores + avalanche level scores

Revision ID: d9e912f97f25
Revises: ff3d57a8536d
Create Date: 2025-05-26 20:09:25.255018

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd9e912f97f25'
down_revision: Union[str, None] = 'ff3d57a8536d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('level_scores', sa.Column('score', sa.Float(), nullable=False))
    op.add_column('level_scores', sa.Column('total_avalanches', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('level_scores', 'total_avalanches')
    op.drop_column('level_scores', 'score')
    # ### end Alembic commands ###
