"""Terrain NO unique name

Revision ID: ea2c0ad3bb49
Revises: 314a40857cc2
Create Date: 2025-04-26 14:23:24.148613

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ea2c0ad3bb49'
down_revision: Union[str, None] = '314a40857cc2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('terrains_name_key', 'terrains', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('terrains_name_key', 'terrains', ['name'])
    # ### end Alembic commands ###
